services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ocean-hiring-backend
    ports:
      - "8000:8000"
    volumes:
      # Mount the data folder from host to container
      - ./data:/app/data:rw  # Read-write mount since backend may save analysis results
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - compatibility-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ocean-hiring-ui
    ports:
      - "5005:5005"
    volumes:
      # Mount the data folder from host to container
      - ./data:/app/data:rw  # Read-write mount since UI may save analysis results
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - API_BASE_URL=http://backend:8000
    restart: unless-stopped
    networks:
      - compatibility-network
    depends_on:
      backend:
        condition: service_healthy

networks:
  compatibility-network:
    driver: bridge

volumes:
  # Define named volume for data persistence (optional)
  data-volume:
    driver: local 