[project]
name = "tech-europe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "mistralai>=1.7.1",
    "openai>=1.82.0",
    "requests>=2.32.3",
]
